server:
  port: 10010
logging:
  level:
    com.ggy: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
spring:
  application:
    name: gateway-server
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos地址
    gateway:
      routes:
        - id: user-service # 路由标示，必须唯一
          uri: http://localhost:8082 # 路由的目标地址
          predicates: # 路由断言，判断请求是否符合规则
            - Path=/user/** # 路径断言，判断路径是否是以/user开头，如果是则符合
        - id: resource-service
          uri: http://localhost:8081
          predicates:
            - Path=/resource/**
      default-filters:
        - AddRequestHeader=Truth,Itcast is freaking awesome!