server:
  port: 8081
# DataSource Config
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql:///srdemo?userUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
#      discovery:
#        cluster-name: HZ

  application:
    name: resource-service
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos服务地址
  #      discovery: #设置地域，作用有两个，一是提高容灾能力，二是加快访问速度
  #      cluster-name: HZ
  redis:
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # Redis数据库索引（默认为0）
    database: 0
    # 连接超时时间（毫秒）
    timeout: 300
    client-type: lettuce #切换jedis客户端，改成jedis
    lettuce: #切换jedis客户端，改成jedis
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
mybatis-plus:
  configuration:
#    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.ggy: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
feign:
  httpclient:
    enabled: true # 支持HttpClient的开关
    max-connections: 200 # 最大连接数
    max-connections-per-route: 50 # 单个路径的最大连接数